### ISSUE TITLE
how to prevent "exit_context"

### ISSUE THREAD

**Issue by ludybupt** [SWE-agent/SWE-agent#1176]
### Describe the issue
It happens when request local model( SWE-Agent-LM-32B)
config:
```
model:
    name: hosted_vllm/SWEAgentLM32B
    api_base: http://10.78.48.189:4000
    api_key: KEY123
    per_instance_cost_limit: 0   
    total_cost_limit: 0
    per_instance_call_limit: 100
    max_input_tokens: 32000
templates:
    WINDOW: 100
```
<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/c25710d2-4b0f-4f82-aadf-eaf9bed36e9e" />
