### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by Eshe0922** [SWE-agent/SWE-agent#882]
### Describe the bug

Hello， I am trying to use the batch mode following the expert cases. However, I think the example case is incorrect as the `repo` should be the attributes of the `env`.

The incorrect example:
```
- env:
    deployment:
      type: docker
      image: python:3.11
  problem_statement:
    type: text
    text: "A simple test problem"
    id: "simple_test_problem"
  repo:
    type: github
    github_url: "https://github.com/swe-agent/test-repo"
```

The correct example should be:
```
- env:
    deployment:
      type: docker
      image: python:3.11
    repo:
       type: github
       github_url: "https://github.com/swe-agent/test-repo"
    problem_statement:
       type: text
       text: "A simple test problem"
       id: "simple_test_problem"
```

### Steps/commands/code to Reproduce

Skip

### Error message/results

Skip

### System Information

Skip

### Checklist

- [x] I'm running with the latest docker container/on the latest development version (i.e., I ran `git pull`))
- [x] I have copied the full command/code that I ran (as text, not as screenshot!)
- [x] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [x] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.
